version: '3.8'

services:
  # Redis Service for Queues
  redis:
    image: "redis:alpine" # Use a lightweight Redis image
    container_name: quickfund_redis
    ports:
      - "6379:6379" # Map port 6379 on your machine to port 6379 in the container
    volumes:
      - redis_data:/data

volumes:
  redis_data: